<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function govcan_metatag_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_theme().
 */
function govcan_metatag_theme() {
  $info['govcan_metatag'] = array(
    'render element' => 'element',
  );
  $info['govcan_metatag_scheme'] = array(
    'render element' => 'element',
  );
  return $info;
}

/**
 * Theme callback for an GovCan meta tag.
 */
function theme_govcan_metatag($variables) {
  $element = &$variables['element'];
  element_set_attributes($element, array('#name' => 'property', '#value' => 'content'));
  unset($element['#value']);
  return theme_html_tag($variables);
}

/**
 * Theme callback for an GovCan meta tag.
 */
function theme_govcan_metatag_scheme($variables) {
  $element = &$variables['element'];
  element_set_attributes($element, array('#name' => 'property', '#value' => 'content'));
  $element['#attributes']['scheme'] = 'W3CDTF';
  unset($element['#value']);
  return theme_html_tag($variables);
}