<?php

/**
 * @file
 * The Node export CSV module.
 *
 * Adds CSV format to Node export.
 */

/**
 * Implements hook_node_export_format_handlers().
 *
 * @see hook_node_export_format_handlers()
 */
function node_export_csv_node_export_format_handlers() {
  return array(
    'csv' => array(
      '#title' => t('CSV'),
      '#module' => 'node_export_csv',
    ),
  );
}

/**
 * Implements hook_node_export().
 *
 * @see hook_node_export()
 */
function node_export_csv_node_export($nodes, $format) {
  return node_export_csv_encode($nodes);
}

/**
 * Build CSV string.
 */
function node_export_csv_encode($nodes) {
  $header = array();
  $encoded_nodes = array();

  $csv_lines = array();

  foreach ($nodes as $node_key => &$node) {
    $encoded_nodes[$node_key] = array();
    node_export_csv_encode_node($header, $encoded_nodes, $node_key, $node);
  }

  $csv_lines[0] = $header;

  foreach ($encoded_nodes as $encoded_node_key => &$encoded_node) {
    $csv_line = array();
    $line = $encoded_node_key + 1;
    foreach ($header as $header_key => $header_value) {
      $value = '';
      if (isset($encoded_node[$header_value])) {
        $value = $encoded_node[$header_value];
      }
      $csv_line[] = $value;
    }
    $csv_lines[$line] = $csv_line;
  }

  return node_export_csv_array_to_csv($csv_lines);
}

/**
 * Process a node and update $header and $encoded_nodes accordingly.
 */
function node_export_csv_encode_node(&$header, &$encoded_nodes, $node_key, $var, $parents = NULL) {
  static $last_header = NULL;

  foreach ($var as $k => &$v) {

    // Get the new header value.
    $header_value = node_export_csv_encode_header_value($parents, $var, $k);

    if (is_object($v) || is_array($v)) {
      // Recurse through the structure.
      node_export_csv_encode_node($header, $encoded_nodes, $node_key, $v, $header_value);
    }
    else {
      // Insert $header_value into the header.
      $position = node_export_csv_encode_array_insert_after($header, $header_value, $last_header);

      // Create a safe text version of this value and store it against the header using a safe key.
      $encoded_nodes[$node_key][$header_value] = node_export_csv_encode_sanitize_value($v);

      // Update $last_header for the next iteration.
      $last_header = $header_value;
    }
  }
}

/**
 * Create header value from $parents, $var, and $k.
 */
function node_export_csv_encode_sanitize_value($var) {
    if (is_numeric($var)) {
      return $var;
    }
    elseif (is_bool($var)) {
      return ($var ? 'TRUE' : 'FALSE');
    }
    elseif (is_null($var)) {
      return 'NULL';
    }
    elseif (is_string($var)) {
      //return '"'. $var .'"';
      return "'" . strtr($var, array("'" => "\\'")) . "'";
    }
    else {
      return '';
    }

}

/**
 * Create header value from $parents, $var, and $k.
 */
function node_export_csv_encode_header_value($parents, $var, $k) {
  if (is_null($parents)) {
    // Special case; on the first level do not prefix the key.
    $header_value = $k;
  }
  elseif (is_object($var)) {
    $header_value = $parents . "->" . $k;
  }
  elseif (is_array($var)) {
    $header_value = $parents . "['" . $k . "']";
  }
  return $header_value;
}

/**
 * Insert $new after $before in $array if not exists, and return the position.
 */
function node_export_csv_encode_array_insert_after(&$array, $new, $before) {
  $position = array_search($new, $array);
  if ($position === FALSE) {
    $position = array_search($before, $array) + 1;
    if ($position >= count($array)) {
      // Just append.
      $array[] = $new;
    }
    else {
      // Insert.
      node_export_csv_encode_array_insert_at($array, $new, $position);
    }
  }
  return $position;
}

/**
 * Insert $new at $position in $array.
 */
function node_export_csv_encode_array_insert_at(&$array, $new, $position) {
  $prefix = array_slice($array, 0, $position);
  $suffix = array_slice($array, $position);
  $array = array_merge($prefix, array($new), $suffix);
}

/**
 * Implements hook_node_export_import().
 *
 * @see hook_node_export_import()
 */
function node_export_csv_node_export_import($code_string) {

  // Get array data from CSV.
  $array = @node_export_csv_csv_to_array($code_string);

  // If the first two rows are of equal length, we can assume this is a CSV.
  // Also checks there are a decent number of fields.
  if (count($array[0]) > 10 && count($array[0]) == count($array[1])) {
    $nodes = array();

    // Assume row 0 is the header, and the rest of the rows are the nodes.
    $header = array_shift($array);

    // Build the nodes.
    foreach ($array as &$row) {
      $node = (object)array();
      foreach ($row as $key => $item) {
        eval('$node->' . $header[$key] . ' = ' . $item . ';');
      }
      $nodes[] = $node;
    }

    return $nodes;
  }
}

/**
 *  Encode RFC4180 compliant CSV.
 */
function node_export_csv_array_to_csv($array, $seperator = ',', $enclosure = '"', $eol = "\r\n") {
  $lines = array();
  foreach ($array as $line) {
    $out_item = array();
    foreach ($line as $item) {
      if (stripos($item, $enclosure) !== FALSE) {
        $item = str_replace($enclosure, $enclosure . $enclosure, $item);
      }
      if (
        (stripos($item, $seperator) !== FALSE)
        || (stripos($item, $enclosure) !== FALSE)
        || (stripos($item, $eol) !== FALSE)
      ) {
        $item = $enclosure . $item . $enclosure;
      }
      $out_item[] = $item;
    }
    $lines[] = implode($seperator, $out_item);
  }
  return implode($eol, $lines);
}

/**
 *  Decode RFC4180 compliant CSV.
 */
function node_export_csv_csv_to_array($string, $seperator = ',', $enclosure = '"', $eol = "\r\n") {
  $lines = array();
  $out_item = array();
  $count = strlen($string);
  $escape = FALSE;
  $double_escape = FALSE;
  $position = 0;
  $i = 0;
  $eols = str_split($eol);

  while ($i < $count) {
    $c = $string[$i];

    // Determine whether this is an EOL.
    $is_eol = TRUE;
    for ($j = 0; $j < count($eols); $j++) {
      if (!isset($string[$i + $j]) || $string[$i + $j] != $eols[$j]) {
        $is_eol = FALSE;
        break;
      }
    }

    if ($is_eol) {
      if ($escape) {
        $out_item[$position] .= $c;
      }
      else {
        $i += count($eols);
        $lines[] = $out_item;
        $out_item = array();
        $position = 0;
        continue;
      }
    }
    elseif ($c == $seperator) {
      if ($escape) {
        $out_item[$position] .= $c;
      }
      else {
        $position++;
        $escape = FALSE;
        $double_escape = FALSE;
      }
    }
    elseif ($c == $enclosure) {
      if ($double_escape) {
        $out_item[$position] .= $enclosure;
        $double_escape = FALSE;
      }
      if ($escape) {
        $escape = FALSE;
        $double_escape = TRUE;
      }
      else {
        $escape = TRUE;
        $double_escape = FALSE;
      }
    }
    else {
      if ($double_escape) {
        $out_item[$position] .= $enclosure;
        $double_escape = FALSE;
      }
      $out_item[$position] .= $c;
    }
    $i++;
  }
  if (!empty($out_item)) {
    $lines[] = $out_item;
  }
  return $lines;
}
