<?php
/**
 * @file
 * Code for the statcan_health_indicator feature.
 */

include_once('statcan_health_indicator.features.inc');

function statcan_health_indicator_install() {
  taxonomy_vocabulary_save((object) array(
    'name' => 'Health Indicators',
    'machine_name' => 'health_indicators',
  ));
}

function statcan_health_indicator_node_view($node) {
  if ($node->type == 'health_indicators')
  {
    drupal_add_js('sites/all/themes/clf_custom/js/pe-ap.js', 'file');
    drupal_add_js('sites/all/themes/clf_custom/js/tabs.js', 'file');
  }
}

function statcan_health_indicator_node_presave($node) {
  dsm("Node PreSave Called");
  if ($node->type == 'health_indicators')
  {
    if ($node->language == 'und' || $node->language == 'en')
    {
      $lang_ext = 'eng.htm';
    }
    else
    {
      $lang_ext = 'fra.htm';
    }
    foreach ($node->field_tables_key['und'] as $delta => $item){
      
      $url = 'http://www40.statcan.gc.ca/cbin/fl/cstincludetxt.cgi?filename=' . $node->field_tables_key['und'][$delta]['value'] . '-' . $lang_ext;
      //if (file_exists($url))
      //{
      $file = file_get_contents($url);
      //$file_safe = check_plain($file);
      //$html_text = '<div id="graphit' . $delta . '">' . $file_safe . '</div>';
      $html_text = '<div id="graphit' . $delta . '">' . $file . '</div>';
      $node->field_tables['und'][$delta]['value'] = $html_text; 
      //}
    }
  }
}

function statcan_health_indicator_overlay_child_initialize() {
  drupal_add_css(drupal_get_path('module', 'statcan_health_indicator') .'/statcan_health_indicator.css');
}

/**
* Implements hook_admin_paths_alter().
*/
function statcan_health_indicator_admin_paths_alter(&$paths) {
  $paths['node/*/edit'] = TRUE;
}